---
language: node_js
#languae node_js
addons:
  sauce_connect: true

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

notifications:
  campfire:
    secure: "JJezWGD9KJY/LC2aznI3Zyohy31VTIhcTKX7RWR4C/C8YKbW9kZv3xV6Vn11\nSHxJTeZo6st2Bpv6tjlWZ+HCR09kyCNavIChedla3+oHOiuL0D4gSo+gkTNW\nUKYZz9mcQUd9RoQpTeyxvdvX+l7z62/7JwFA7txHOqxbTS8jrjc="

before_deploy:
  - ASSETS_HOST=https://s3.amazonaws.com/travis-error-pages ember build --env production
  # delete some of the stuff that's useless for maintenance page
  - rm -fr dist/assets/*.js dist/images/emoji dist/index.html dist/images/sponsors
  - cp dist/maintenance.html dist/index.html

deploy:
  provider: s3
  access_key_id: $MAINTENANCE_S3_ACCESS_KEY_ID
  secret_access_key: $MAINTENANCE_S3_SECRET_ACCESS_KEY
  bucket: travis-error-pages
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  region: us-east-1
